<a href="https://colab.research.google.com/github/BFvandy/Nissan-Text-Mining-POC-with-Transformer/blob/main/Reddit%26SW%26Cars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prep

In [ ]:
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
cur_path = "/content/drive/My Drive/Nissan Internship/SW 2020-2022 Verbatim Small SUV"
os.chdir(cur_path)
!pwd

/content/drive/My Drive/Nissan Internship/SW 2020-2022 Verbatim Small SUV

# Load Data

In [ ]:
cmt_SW = pd.read_csv('SW_score_v3.csv')

In [ ]:
pd.set_option('display.max_columns', None)
cmt_SW

,Unnamed: 0,Make,Model,Source,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Text,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
0,0,Honda,CR-V,Strategic Window,Honda CR-V Special Edition FWD,2022,2021,Honda Civic,2019.0,Honda HR-V,2022.0,Sentiment Not Calculated,Age 41,Female,White,Income Unknown,The engine start stop/ gas save mode is not ve...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Nissan,Rogue,Strategic Window,Nissan Rogue SV AWD,2022,2021,Ford Fusion,2012.0,Toyota Highlander,2021.0,Sentiment Not Calculated,Age 35,Male,White,"$100,001 - $125,000",We were not told the price of the vehicle goin...,NaN,NaN,0.029433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.011031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Nissan,Rogue,Strategic Window,Nissan Rogue S AWD,2022,2021,Chevrolet Spark,2016.0,Hyundai Santa Fe,2021.0,Sentiment Not Calculated,Age 57,Male,White,Income Unknown,My Nissan Rogue is the perfect balance between...,NaN,NaN,NaN,0.984863,0.98799,NaN,NaN,NaN,0.997018,NaN,0.993778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.974088,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L FWD,2022,2022,Nissan Versa Note (Hatchback),2018.0,Lexus LX,2022.0,Sentiment Not Calculated,Age 49,Female,Asian,"$65,001 - $70,000",I wish :\n1.there is a CD player installed. T...,NaN,0.640963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L FWD,2022,2022,(None),NaN,Honda Civic,2015.0,Sentiment Not Calculated,Age 54,Female,White,"$200,001 - $300,000","The 2022 Honda CRV is a nice looking car, with...",NaN,NaN,NaN,NaN,NaN,0.048322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106999,106999,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L FWD,2020,2020,None,18.0,None,16.0,Sentiment Not Calculated,Age 34,Female,Hispanic,"$150,001 - $175,000",G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107000,107000,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L AWD,2020,2019,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107001,107001,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L AWD,2020,2019,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107002,107002,Honda,CR-V,Strategic Window,Honda CR-V LX FWD,2020,2019,Honda CR-V,2015.0,Honda HR-V,2019.0,Sentiment Not Calculated,Age 59,Male,White,"$50,001 - $55,000",I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107003,107003,Nissan,Rogue,Strategic Window,Nissan Rogue SV AWD,2020,2020,(None),NaN,(None),NaN,Sentiment Not Calculated,Age Unknown,Female,White,Income Unknown,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import os
cur_path = "/content/drive/My Drive/Nissan Internship/Reddit Comments"
os.chdir(cur_path)
!pwd

/content/drive/My Drive/Nissan Internship/Reddit Comments

In [ ]:
cmt_Reddit = pd.read_csv('reddit_score_v2.csv')

In [ ]:
pd.set_option('display.max_columns', None)
cmt_Reddit

,Unnamed: 0,Make,Model,Source,Text,timestamp,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
0,0,Nissan,Rogue,Reddit,This is incredible timing for me as my cvt jus...,1.659024e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Nissan,Rogue,Reddit,Op do you own it out right? i'd sell it or tra...,1.659036e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Nissan,Rogue,Reddit,I have 2019 sport transmission failed at 42k m...,1.659033e+09,0.187838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.584861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Nissan,Rogue,Reddit,Not yet. but i bought an extended warranty any...,1.659030e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Nissan,Rogue,Reddit,My 2016 maxima cvt took a shit at 85k miles lu...,1.659037e+09,0.310584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.978874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28376,28376,Toyota,RAV4,Reddit,"I would maybe wait for the fall, just so your ...",1.625451e+09,NaN,0.863397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28377,28377,Toyota,RAV4,Reddit,Yeah i probably will just wait until september...,1.625464e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28378,28378,Toyota,RAV4,Reddit,Change it.,1.637008e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28379,28379,Toyota,RAV4,Reddit,Did plenty of drain and fills on higher mileag...,1.637016e+09,0.938793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.831673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28380,28380,Toyota,RAV4,Reddit,Yes change it,1.637035e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Add Average

In [ ]:
cmt_Reddit.loc['mean'] = data_concat.mean()
cmt_Reddit

KeyboardInterrupt: ignored

# Concat

In [ ]:
data_concat = pd.concat([cmt_SW, cmt_Reddit],
                      ignore_index = True,
                      sort = False)
data_concat

,Unnamed: 0,Make,Model,Source,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Text,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive,timestamp
0,0,Honda,CR-V,Strategic Window,Honda CR-V Special Edition FWD,2022.0,2021.0,Honda Civic,2019.0,Honda HR-V,2022.0,Sentiment Not Calculated,Age 41,Female,White,Income Unknown,The engine start stop/ gas save mode is not ve...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Nissan,Rogue,Strategic Window,Nissan Rogue SV AWD,2022.0,2021.0,Ford Fusion,2012.0,Toyota Highlander,2021.0,Sentiment Not Calculated,Age 35,Male,White,"$100,001 - $125,000",We were not told the price of the vehicle goin...,NaN,NaN,0.029433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.011031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Nissan,Rogue,Strategic Window,Nissan Rogue S AWD,2022.0,2021.0,Chevrolet Spark,2016.0,Hyundai Santa Fe,2021.0,Sentiment Not Calculated,Age 57,Male,White,Income Unknown,My Nissan Rogue is the perfect balance between...,NaN,NaN,NaN,0.984863,0.98799,NaN,NaN,NaN,0.997018,NaN,0.993778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.974088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L FWD,2022.0,2022.0,Nissan Versa Note (Hatchback),2018.0,Lexus LX,2022.0,Sentiment Not Calculated,Age 49,Female,Asian,"$65,001 - $70,000",I wish :\n1.there is a CD player installed. T...,NaN,0.640963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L FWD,2022.0,2022.0,(None),NaN,Honda Civic,2015.0,Sentiment Not Calculated,Age 54,Female,White,"$200,001 - $300,000","The 2022 Honda CRV is a nice looking car, with...",NaN,NaN,NaN,NaN,NaN,0.048322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135380,28376,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I would maybe wait for the fall, just so your ...",NaN,0.863397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.625451e+09
135381,28377,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yeah i probably will just wait until september...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.625464e+09
135382,28378,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Change it.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.637008e+09
135383,28379,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Did plenty of drain and fills on higher mileag...,0.938793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.831673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.637016e+09
135384,28380,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes change it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.637035e+09

In [ ]:
data_concat.groupby(['Source']).count()

,Unnamed: 0,Make,Model,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Text,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive,timestamp
Source,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Reddit,28381,28381,28381,0,0,0,0,0,0,0,0,0,0,0,0,28281,1481,1806,934,1404,791,769,510,1013,480,1272,992,1177,1186,937,410,466,839,882,401,2379,997,962,851,1750,948,732,1892,747,1176,28381
Strategic Window,107004,107004,107004,107004,107004,107004,107004,76693,107004,55588,107004,107004,107004,103410,107004,104167,16745,7218,4894,9237,7306,9473,2548,10760,8709,10703,7821,10613,2502,5813,729,1204,4315,11024,764,7173,7359,3868,5212,9014,4708,6607,10672,1872,5409,0

In [ ]:
SW_concat = data_concat.iloc[:107004,:]
SW_concat = SW_concat.drop(SW_concat.iloc[:,0:1],axis = 1)
SW_concat

,Make,Model,Source,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Text,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive,timestamp
0,Honda,CR-V,Strategic Window,Honda CR-V Special Edition FWD,2022.0,2021.0,Honda Civic,2019.0,Honda HR-V,2022.0,Sentiment Not Calculated,Age 41,Female,White,Income Unknown,The engine start stop/ gas save mode is not ve...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Nissan,Rogue,Strategic Window,Nissan Rogue SV AWD,2022.0,2021.0,Ford Fusion,2012.0,Toyota Highlander,2021.0,Sentiment Not Calculated,Age 35,Male,White,"$100,001 - $125,000",We were not told the price of the vehicle goin...,NaN,NaN,0.029433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.011031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nissan,Rogue,Strategic Window,Nissan Rogue S AWD,2022.0,2021.0,Chevrolet Spark,2016.0,Hyundai Santa Fe,2021.0,Sentiment Not Calculated,Age 57,Male,White,Income Unknown,My Nissan Rogue is the perfect balance between...,NaN,NaN,NaN,0.984863,0.98799,NaN,NaN,NaN,0.997018,NaN,0.993778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.974088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L FWD,2022.0,2022.0,Nissan Versa Note (Hatchback),2018.0,Lexus LX,2022.0,Sentiment Not Calculated,Age 49,Female,Asian,"$65,001 - $70,000",I wish :\n1.there is a CD player installed. T...,NaN,0.640963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L FWD,2022.0,2022.0,(None),NaN,Honda Civic,2015.0,Sentiment Not Calculated,Age 54,Female,White,"$200,001 - $300,000","The 2022 Honda CRV is a nice looking car, with...",NaN,NaN,NaN,NaN,NaN,0.048322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106999,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L FWD,2020.0,2020.0,None,18.0,None,16.0,Sentiment Not Calculated,Age 34,Female,Hispanic,"$150,001 - $175,000",G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107000,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L AWD,2020.0,2019.0,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107001,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L AWD,2020.0,2019.0,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107002,Honda,CR-V,Strategic Window,Honda CR-V LX FWD,2020.0,2019.0,Honda CR-V,2015.0,Honda HR-V,2019.0,Sentiment Not Calculated,Age 59,Male,White,"$50,001 - $55,000",I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107003,Nissan,Rogue,Strategic Window,Nissan Rogue SV AWD,2020.0,2020.0,(None),NaN,(None),NaN,Sentiment Not Calculated,Age Unknown,Female,White,Income Unknown,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
SW_concat.loc['Mean'] = SW_concat.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

In [ ]:
SW_concat.loc['Mean','Source'] = 'Strategic Window'
SW_concat.loc['Mean','Model'] = 'Mean'
SW_concat.loc['Mean','Make'] = 'Mean'

In [ ]:
SW_concat

,Make,Model,Source,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Text,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive,timestamp
0,Honda,CR-V,Strategic Window,Honda CR-V Special Edition FWD,2022.000000,2021.000000,Honda Civic,2019.000000,Honda HR-V,2022.000000,Sentiment Not Calculated,Age 41,Female,White,Income Unknown,The engine start stop/ gas save mode is not ve...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Nissan,Rogue,Strategic Window,Nissan Rogue SV AWD,2022.000000,2021.000000,Ford Fusion,2012.000000,Toyota Highlander,2021.000000,Sentiment Not Calculated,Age 35,Male,White,"$100,001 - $125,000",We were not told the price of the vehicle goin...,NaN,NaN,0.029433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.011031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nissan,Rogue,Strategic Window,Nissan Rogue S AWD,2022.000000,2021.000000,Chevrolet Spark,2016.000000,Hyundai Santa Fe,2021.000000,Sentiment Not Calculated,Age 57,Male,White,Income Unknown,My Nissan Rogue is the perfect balance between...,NaN,NaN,NaN,0.984863,0.987990,NaN,NaN,NaN,0.997018,NaN,0.993778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.974088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L FWD,2022.000000,2022.000000,Nissan Versa Note (Hatchback),2018.000000,Lexus LX,2022.000000,Sentiment Not Calculated,Age 49,Female,Asian,"$65,001 - $70,000",I wish :\n1.there is a CD player installed. T...,NaN,0.640963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L FWD,2022.000000,2022.000000,(None),NaN,Honda Civic,2015.000000,Sentiment Not Calculated,Age 54,Female,White,"$200,001 - $300,000","The 2022 Honda CRV is a nice looking car, with...",NaN,NaN,NaN,NaN,NaN,0.048322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107000,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L AWD,2020.000000,2019.000000,GMC Terrain,2013.000000,Honda CR-V,2020.000000,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107001,Honda,CR-V,Strategic Window,Honda CR-V EX/EX-L AWD,2020.000000,2019.000000,GMC Terrain,2013.000000,Honda CR-V,2020.000000,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107002,Honda,CR-V,Strategic Window,Honda CR-V LX FWD,2020.000000,2019.000000,Honda CR-V,2015.000000,Honda HR-V,2019.000000,Sentiment Not Calculated,Age 59,Male,White,"$50,001 - $55,000",I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107003,Nissan,Rogue,Strategic Window,Nissan Rogue SV AWD,2020.000000,2020.000000,(None),NaN,(None),NaN,Sentiment Not Calculated,Age Unknown,Female,White,Income Unknown,I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mean,Mean,Mean,Strategic Window,NaN,2020.853977,2020.606968,NaN,1997.588085,NaN,1978.190761,NaN,NaN,NaN,NaN,NaN,NaN,0.898957,0.782536,0.867590,0.912579,0.926546,0.905916,0.858508,0.858362,0.952908,0.881519,0.867159,0.819437,0.773429,0.770298,0.641949,0.611701,0.790213,0.947617,0.689103,0.861472,0.844302,0.636042,0.820744,0.857177,0.568932,0.893131,0.842958,0.248076,0.411298,NaN

In [ ]:
SW_concat.to_csv('SW_score_v4.csv', index = 'False')

In [ ]:
Reddit_concat = data_concat.iloc[107004:,:]
Reddit_concat = Reddit_concat.drop(Reddit_concat.iloc[:,0:1],axis = 1)
Reddit_concat

,Make,Model,Source,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Text,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive,timestamp
107004,Nissan,Rogue,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This is incredible timing for me as my cvt jus...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.659024e+09
107005,Nissan,Rogue,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Op do you own it out right? i'd sell it or tra...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.659036e+09
107006,Nissan,Rogue,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have 2019 sport transmission failed at 42k m...,0.187838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.584861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.659033e+09
107007,Nissan,Rogue,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not yet. but i bought an extended warranty any...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.659030e+09
107008,Nissan,Rogue,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,My 2016 maxima cvt took a shit at 85k miles lu...,0.310584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.978874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.659037e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135380,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I would maybe wait for the fall, just so your ...",NaN,0.863397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.625451e+09
135381,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yeah i probably will just wait until september...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.625464e+09
135382,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Change it.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.637008e+09
135383,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Did plenty of drain and fills on higher mileag...,0.938793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.831673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.637016e+09
135384,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes change it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.637035e+09

In [ ]:
Reddit_concat.loc['Mean'] = Reddit_concat.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

In [ ]:
Reddit_concat.loc['Mean','Source'] = 'Reddit'
Reddit_concat.loc['Mean','Model'] = 'Mean'
Reddit_concat.loc['Mean','Make'] = 'Mean'

In [ ]:
Reddit_concat

,Make,Model,Source,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Text,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive,timestamp
107004,Nissan,Rogue,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This is incredible timing for me as my cvt jus...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.659024e+09
107005,Nissan,Rogue,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Op do you own it out right? i'd sell it or tra...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.659036e+09
107006,Nissan,Rogue,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have 2019 sport transmission failed at 42k m...,0.187838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.584861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.659033e+09
107007,Nissan,Rogue,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not yet. but i bought an extended warranty any...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.659030e+09
107008,Nissan,Rogue,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,My 2016 maxima cvt took a shit at 85k miles lu...,0.310584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.978874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.659037e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135381,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yeah i probably will just wait until september...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.625464e+09
135382,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Change it.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.637008e+09
135383,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Did plenty of drain and fills on higher mileag...,0.938793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.831673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.637016e+09
135384,Toyota,RAV4,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes change it,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.637035e+09
Mean,Mean,Mean,Reddit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.477346,0.680347,0.542366,0.613381,0.669343,0.455401,0.632589,0.499187,0.801508,0.755139,0.60602,0.542451,0.611304,0.386717,0.566439,0.349907,0.498637,0.636112,0.453485,0.768936,0.325237,0.470937,0.661302,0.669555,0.646254,0.73876,0.653547,0.241103,0.558345,1.640906e+09

In [ ]:
Reddit_concat.to_csv('Reddit_score_v4.csv', index = 'False')

In [ ]:
data_concat.to_csv('data_concat_v1.csv', index = 'False')

# calculate average

In [ ]:
sw_avg = cmt_SW.groupby(['Model']).mean()
sw_avg

,Unnamed: 0,Study Year,Purchased Year,Disposed Model Year,Rejected Model Year,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
Model,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Bronco Sport,32774.275733,2021.304282,2021.108941,2014.289885,2020.700176,0.882312,0.718287,0.870106,0.892740,0.930734,0.853466,0.801264,0.858233,0.974851,0.911304,0.827505,0.810058,0.652727,0.849312,0.747280,0.624029,0.795532,0.902748,0.869079,0.873072,0.796981,0.719859,0.896726,0.846879,0.818586,0.940470,0.862291,0.379234,0.591596
CR-V,52847.714602,2020.871483,2020.572004,1999.274263,1981.145574,0.905740,0.791154,0.867009,0.916436,0.910914,0.905718,0.870574,0.857626,0.946158,0.871965,0.867618,0.820025,0.785008,0.768320,0.623513,0.614410,0.781764,0.954497,0.678683,0.861916,0.848937,0.600738,0.795664,0.856487,0.536027,0.890231,0.835455,0.232201,0.399029
CX-5,56033.150685,2020.754822,2020.525021,1986.504244,2003.647623,0.910921,0.757342,0.899587,0.902672,0.944503,0.918300,0.813528,0.838414,0.972862,0.903338,0.869897,0.868748,0.731310,0.717772,0.735076,0.596112,0.829777,0.931581,0.720836,0.860096,0.859381,0.681989,0.880516,0.834276,0.691561,0.903524,0.884950,0.275310,0.430861
Equinox,64803.855138,2020.634224,2020.647804,1943.047957,1782.553131,0.863649,0.754878,0.883660,0.864377,0.942623,0.901692,0.791162,0.870809,0.959784,0.870128,0.867916,0.795061,0.880975,0.799280,0.741106,0.511105,0.845271,0.937735,0.781865,0.803729,0.843497,0.665944,0.874526,0.852557,0.620667,0.892763,0.824903,0.260889,0.397604
Escape,60780.962714,2020.683374,2020.340465,2013.933795,1970.484716,0.864914,0.746425,0.803902,0.877918,0.920938,0.878138,0.739217,0.855530,0.945020,0.866509,0.852406,0.744054,0.772990,0.792768,0.634938,0.467253,0.694185,0.929554,0.672172,0.806481,0.815746,0.575912,0.745626,0.837210,0.555083,0.885655,0.772776,0.218062,0.398756
Forester,58013.240745,2020.728445,2020.670408,2002.438863,1957.825035,0.907686,0.800092,0.873132,0.932207,0.925128,0.922978,0.898036,0.860519,0.948065,0.899728,0.865304,0.855068,0.755357,0.742506,0.671634,0.649044,0.832992,0.947975,0.705168,0.893767,0.850477,0.657982,0.825255,0.877641,0.571480,0.886009,0.866615,0.248114,0.419798
RAV4,59654.961487,2020.720784,2020.603918,1990.530138,1958.528592,0.905102,0.794865,0.837217,0.896175,0.951371,0.899730,0.863097,0.840556,0.952296,0.876493,0.853845,0.801741,0.696915,0.835433,0.670565,0.673560,0.728020,0.933659,0.743402,0.872871,0.864989,0.572370,0.790700,0.852644,0.530735,0.917337,0.860341,0.255858,0.418468
Rogue,52242.069464,2020.882350,2020.619166,1997.656788,1988.753085,0.868465,0.749409,0.866012,0.909347,0.954620,0.906433,0.804494,0.869048,0.970393,0.905532,0.875943,0.816789,0.766203,0.789234,0.665069,0.611208,0.812089,0.923555,0.686049,0.863725,0.821294,0.733363,0.880412,0.868933,0.637676,0.899394,0.866043,0.281842,0.438373
Sportage,63850.659135,2020.634603,2020.897999,1991.051664,1962.942708,0.865616,0.765016,0.859676,0.876308,0.945519,0.869217,0.732581,0.831821,0.946697,0.877180,0.860968,0.775404,0.651393,0.735145,0.790928,0.449905,0.764384,0.867145,0.645883,0.856689,0.819791,0.627180,0.831670,0.825856,0.550696,0.889976,0.817828,0.271839,0.385783
Tucson,51930.533013,2020.879755,2021.237429,2001.209507,1977.533113,0.863704,0.769148,0.881330,0.905656,0.948621,0.896340,0.868494,0.849575,0.959136,0.892472,0.835738,0.770983,0.728890,0.651226,0.518292,0.669282,0.814078,0.933783,0.753214,0.846192,0.833760,0.704848,0.832633,0.843630,0.587631,0.872732,0.826589,0.333694,0.441761

In [ ]:
sw_count = cmt_SW.groupby(['Model']).count()
sw_count

,Unnamed: 0,Make,Source,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Text,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
Model,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Bronco Sport,1331,1331,1331,1331,1331,1331,1331,959,1331,567,1331,1331,1331,1289,1331,1171,115,74,37,74,125,66,19,99,145,99,77,83,22,53,11,7,53,58,7,66,61,54,80,95,81,97,108,25,62
CR-V,68746,68746,68746,68746,68746,68746,68746,49551,68746,35288,68746,68746,68746,66316,68746,66832,12139,5091,3184,6156,4175,6337,1883,7037,5435,6782,5223,7308,1610,4213,487,824,2712,8093,508,4789,5130,2413,3169,6005,2981,4260,7057,1220,3531
CX-5,3577,3577,3577,3577,3577,3577,3577,2592,3577,2293,3577,3577,3577,3460,3577,3488,418,160,215,358,369,331,54,362,411,436,327,393,75,140,42,42,163,327,28,223,218,126,190,295,195,198,373,43,216
Equinox,2209,2209,2209,2209,2209,2209,2209,1689,2209,1054,2209,2209,2209,2147,2209,2183,218,121,74,146,150,121,33,174,169,160,121,136,47,80,7,18,84,125,13,134,94,57,91,145,89,143,163,34,74
Escape,1636,1636,1636,1636,1636,1636,1636,1299,1636,687,1636,1636,1636,1596,1636,1609,188,111,58,134,106,91,25,155,141,133,111,130,47,74,9,16,66,108,10,82,95,57,65,129,77,122,138,29,70
Forester,4187,4187,4187,4187,4187,4187,4187,3165,4187,2149,4187,4187,4187,4066,4187,3919,608,237,177,351,261,611,101,446,361,487,296,434,71,168,32,68,133,449,24,252,280,135,197,296,201,232,401,59,171
RAV4,3012,3012,3012,3012,3012,3012,3012,2107,3012,1364,3012,3012,3012,2938,3012,2941,515,226,112,250,214,253,75,277,224,269,198,304,75,148,21,12,96,332,25,221,213,112,153,249,134,187,292,56,138
Rogue,18470,18470,18470,18470,18470,18470,18470,12485,18470,10210,18470,18470,18470,17885,18470,18237,1993,922,813,1463,1601,1350,268,1874,1525,1926,1190,1486,453,791,98,184,807,1243,124,1109,1053,774,1062,1456,791,1132,1761,341,947
Sportage,1549,1549,1549,1549,1549,1549,1549,1142,1549,768,1549,1549,1549,1494,1549,1528,208,107,92,102,104,107,35,136,111,138,110,113,39,59,8,12,86,94,8,99,74,54,70,127,63,88,135,35,78
Tucson,2287,2287,2287,2287,2287,2287,2287,1704,2287,1208,2287,2287,2287,2219,2287,2259,343,169,132,203,201,206,55,200,187,273,168,226,63,87,14,21,115,195,17,198,141,86,135,217,96,148,244,30,122

In [ ]:
red_avg = cmt_Reddit.groupby(['Model']).mean()
red_avg

,Unnamed: 0,timestamp,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
Model,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Bronco Sport,6855.5,1.622676e+09,0.485600,0.658560,0.457961,0.565762,0.588079,0.454139,0.539831,0.400264,0.817677,0.740252,0.578962,0.480608,0.593118,0.359693,0.658391,0.329499,0.419533,0.595385,0.479866,0.748374,0.374358,0.361617,0.676803,0.635731,0.613300,0.757022,0.610702,0.231878,0.528901
CR-V,9398.0,1.625946e+09,0.514909,0.633365,0.508738,0.582106,0.609125,0.404856,0.598340,0.497637,0.800750,0.725287,0.575070,0.556560,0.538303,0.312608,0.541063,0.284583,0.461976,0.566446,0.382752,0.745128,0.350044,0.460750,0.589844,0.638755,0.660635,0.770072,0.687871,0.202478,0.593003
CX-5,19313.5,1.644331e+09,0.558147,0.665120,0.582455,0.689657,0.723432,0.606217,0.698519,0.535653,0.790735,0.774713,0.643796,0.564880,0.663894,0.415010,0.566057,0.361187,0.515495,0.736600,0.466130,0.795074,0.355182,0.525459,0.728215,0.659997,0.621101,0.698904,0.686149,0.263939,0.528341
Equinox,2312.0,1.582750e+09,0.458822,0.600182,0.511914,0.651576,0.722939,0.413687,0.654668,0.542214,0.848227,0.741092,0.568173,0.547394,0.756085,0.369781,0.558185,0.383117,0.510097,0.633530,0.431473,0.812420,0.259087,0.521871,0.616866,0.690380,0.654890,0.729407,0.622110,0.240143,0.520238
Escape,4084.0,1.638727e+09,0.459542,0.707913,0.556265,0.573596,0.662698,0.413503,0.674814,0.516094,0.822155,0.759971,0.589470,0.562459,0.621474,0.417654,0.583309,0.358982,0.494876,0.664403,0.486494,0.776332,0.310037,0.477347,0.659419,0.645898,0.662242,0.732180,0.631632,0.226820,0.589361
Forester,23141.5,1.652661e+09,0.443789,0.666878,0.531124,0.570147,0.655505,0.425599,0.567830,0.460120,0.826219,0.721933,0.594180,0.519187,0.532868,0.291388,0.589376,0.290585,0.496294,0.616164,0.439686,0.743618,0.313650,0.493368,0.654255,0.697733,0.661315,0.728549,0.686355,0.222629,0.597850
RAV4,26902.0,1.647236e+09,0.530190,0.692446,0.580202,0.689344,0.742555,0.526749,0.679585,0.540874,0.752990,0.773065,0.646474,0.579973,0.644754,0.462465,0.565316,0.397144,0.541225,0.701339,0.459073,0.800990,0.375438,0.479144,0.678689,0.762258,0.641417,0.728142,0.658766,0.267544,0.537400
Rogue,873.5,1.631547e+09,0.435942,0.656906,0.460196,0.549612,0.660179,0.353545,0.617441,0.524757,0.745260,0.758540,0.607002,0.497975,0.572443,0.344478,0.575433,0.312206,0.374638,0.567377,0.477142,0.735797,0.228122,0.433652,0.524803,0.632763,0.582397,0.737313,0.629029,0.239887,0.544623
Sportage,15513.0,1.655513e+09,0.441125,0.718181,0.529469,0.616340,0.666870,0.436134,0.647576,0.484838,0.802520,0.770949,0.610225,0.584684,0.603870,0.412386,0.569547,0.349264,0.493354,0.599477,0.446153,0.761392,0.335485,0.496587,0.661056,0.627081,0.664311,0.757798,0.640428,0.254678,0.562740
Tucson,11817.5,1.649492e+09,0.418140,0.698544,0.593190,0.595303,0.659474,0.431070,0.625438,0.513650,0.830586,0.754283,0.578083,0.505211,0.621052,0.407260,0.504993,0.395062,0.584321,0.594617,0.434186,0.773575,0.286330,0.452309,0.677929,0.668215,0.676641,0.751762,0.652034,0.243341,0.559432

In [ ]:
red_count = cmt_Reddit.groupby(['Model']).count()
red_count

,Unnamed: 0,Make,Source,Text,timestamp,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
Model,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Bronco Sport,3128,3128,3128,3108,3128,100,149,65,138,105,45,39,86,58,130,71,116,91,65,29,36,67,76,33,180,88,101,104,146,120,86,189,75,104
CR-V,1957,1957,1957,1953,1957,104,109,59,84,37,56,27,63,31,69,57,72,53,63,20,28,55,46,15,150,51,46,42,115,57,34,114,43,74
CX-5,3092,3092,3092,3083,3092,191,230,117,193,112,85,54,131,73,186,135,131,151,112,45,51,98,122,49,266,132,104,103,207,102,88,230,86,142
Equinox,1129,1129,1129,1127,1129,61,60,33,60,41,39,21,45,12,53,39,48,31,50,18,24,38,37,20,118,45,40,34,70,40,28,81,33,42
Escape,2415,2415,2415,2410,2415,125,144,80,98,54,57,36,67,25,85,79,99,83,67,28,38,71,80,41,241,91,97,69,144,77,57,184,68,95
Forester,4564,4564,4564,4544,4564,204,214,99,204,101,107,79,151,57,167,128,173,117,120,57,62,107,112,54,345,134,130,108,261,142,112,281,124,167
RAV4,2957,2957,2957,2950,2957,217,251,134,166,79,110,75,142,63,138,132,126,152,121,58,58,126,118,47,290,116,116,98,224,105,76,193,73,158
Rogue,1748,1748,1748,1743,1748,131,133,45,88,30,59,32,70,25,76,73,79,76,56,23,28,45,79,24,176,66,63,47,116,52,42,116,42,65
Sportage,4509,4509,4509,4490,4509,200,320,203,221,141,112,96,166,75,229,163,204,286,167,65,77,153,131,71,342,155,149,147,263,152,133,289,119,199
Tucson,2882,2882,2882,2873,2882,148,196,99,152,91,99,51,92,61,139,115,129,146,116,67,64,79,81,47,271,119,116,99,204,101,76,215,84,130

In [ ]:
with pd.ExcelWriter('avg results.xlsx') as writer:
  sw_avg.to_excel(writer, sheet_name='sw_avg')
  sw_count.to_excel(writer, sheet_name='sw_count')
  red_avg.to_excel(writer, sheet_name='red_avg')
  red_count.to_excel(writer, sheet_name='red_count')

# Car Review Websites Data

In [ ]:
import os
cur_path = "/content/drive/My Drive/Nissan Internship/Car Review Websites"
os.chdir(cur_path)
!pwd

/content/drive/My Drive/Nissan Internship/Car Review Websites

In [ ]:
cars_fun = pd.read_csv('comments_score_ver4_24.csv')
cars_pers = pd.read_csv('comments_score_pers.csv')

In [ ]:
pd.set_option('display.max_columns', None)
cars_fun

,Model,Souce,Comment,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable
0,Rogue,Cars,I’ve had my 2021 Rogue SL with the premium pac...,0.000000,0.977574,0.000000,0.994457,0.0000,0.000000,0.0,0.921304,0.000000,0.00000,0.000000,0.000000,0.000000,0.987648,0.0,0.000000,0.000000
1,Rogue,Cars,I have to preface this by saying I purchased a...,0.000000,0.671533,0.000000,0.000000,0.0000,0.934069,0.0,0.366737,0.000000,0.00000,0.000000,0.000000,0.000000,0.736786,0.0,0.000000,0.099225
2,Rogue,Cars,Recently traded in my 2016 for the new redesig...,0.000000,0.000000,0.972520,0.724667,0.8673,0.000000,0.0,0.000000,0.000000,0.99507,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
3,Rogue,Cars,Meets our needs comfortable stylish love the ...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
4,Rogue,Cars,Always have been a huge fan of Rogues but I ab...,0.994991,0.000000,0.984983,0.000000,0.0000,0.975976,0.0,0.991613,0.000000,0.00000,0.998625,0.966145,0.000000,0.604196,0.0,0.241507,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4634,RAV4,Edmunds,Bought HNov. 21 to drive back and forth from A...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.979899,0.00000,0.916568,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
4635,RAV4,Edmunds,I have a 2021 Rav 4 Hybrid with 6000 kilometer...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
4636,RAV4,Edmunds,The tailgate rattles like no SUV I’ve ever own...,0.981198,0.557962,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.965735,0.000000,0.0,0.000000,0.000000
4637,RAV4,Edmunds,I purchased my 2021 Toyota Rav4 new in August....,0.968101,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
4638,RAV4,Edmunds,"First, the fuel economy is great. Although it ...",0.935105,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.988952,0.0,0.000000,0.000000

In [ ]:
cars_pers

,Model,Souce,Comment,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
0,Rogue,Cars,I’ve had my 2021 Rogue SL with the premium pac...,0.000000,0.000000,0.896185,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Rogue,Cars,I have to preface this by saying I purchased a...,0.376898,0.176889,0.000000,0.000000,0.0,0.505428,0.568424,0.898860,0.720507,0.000000,0.000000,0.674960
2,Rogue,Cars,Recently traded in my 2016 for the new redesig...,0.000000,0.000000,0.806745,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.957378,0.000000,0.000000
3,Rogue,Cars,Meets our needs comfortable stylish love the ...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Rogue,Cars,Always have been a huge fan of Rogues but I ab...,0.997381,0.304090,0.936501,0.853579,0.0,0.000000,0.968310,0.836067,0.978573,0.992617,0.030481,0.036311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4634,RAV4,Edmunds,Bought HNov. 21 to drive back and forth from A...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4635,RAV4,Edmunds,I have a 2021 Rav 4 Hybrid with 6000 kilometer...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4636,RAV4,Edmunds,The tailgate rattles like no SUV I’ve ever own...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4637,RAV4,Edmunds,I purchased my 2021 Toyota Rav4 new in August....,0.000000,0.000000,0.304392,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4638,RAV4,Edmunds,"First, the fuel economy is great. Although it ...",0.000000,0.000000,0.000000,0.000000,0.0,0.278976,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:
cars_kbb = pd.concat([cars_fun, cars_pers], axis=1, join="inner")
cars_kbb

,Model,Souce,Comment,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,Model,Souce,Comment,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
0,Rogue,Cars,I’ve had my 2021 Rogue SL with the premium pac...,0.000000,0.977574,0.000000,0.994457,0.0000,0.000000,0.0,0.921304,0.000000,0.00000,0.000000,0.000000,0.000000,0.987648,0.0,0.000000,0.000000,Rogue,Cars,I’ve had my 2021 Rogue SL with the premium pac...,0.000000,0.000000,0.896185,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Rogue,Cars,I have to preface this by saying I purchased a...,0.000000,0.671533,0.000000,0.000000,0.0000,0.934069,0.0,0.366737,0.000000,0.00000,0.000000,0.000000,0.000000,0.736786,0.0,0.000000,0.099225,Rogue,Cars,I have to preface this by saying I purchased a...,0.376898,0.176889,0.000000,0.000000,0.0,0.505428,0.568424,0.898860,0.720507,0.000000,0.000000,0.674960
2,Rogue,Cars,Recently traded in my 2016 for the new redesig...,0.000000,0.000000,0.972520,0.724667,0.8673,0.000000,0.0,0.000000,0.000000,0.99507,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,Rogue,Cars,Recently traded in my 2016 for the new redesig...,0.000000,0.000000,0.806745,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.957378,0.000000,0.000000
3,Rogue,Cars,Meets our needs comfortable stylish love the ...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,Rogue,Cars,Meets our needs comfortable stylish love the ...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Rogue,Cars,Always have been a huge fan of Rogues but I ab...,0.994991,0.000000,0.984983,0.000000,0.0000,0.975976,0.0,0.991613,0.000000,0.00000,0.998625,0.966145,0.000000,0.604196,0.0,0.241507,0.000000,Rogue,Cars,Always have been a huge fan of Rogues but I ab...,0.997381,0.304090,0.936501,0.853579,0.0,0.000000,0.968310,0.836067,0.978573,0.992617,0.030481,0.036311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4634,RAV4,Edmunds,Bought HNov. 21 to drive back and forth from A...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.979899,0.00000,0.916568,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,RAV4,Edmunds,Bought HNov. 21 to drive back and forth from A...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4635,RAV4,Edmunds,I have a 2021 Rav 4 Hybrid with 6000 kilometer...,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,RAV4,Edmunds,I have a 2021 Rav 4 Hybrid with 6000 kilometer...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4636,RAV4,Edmunds,The tailgate rattles like no SUV I’ve ever own...,0.981198,0.557962,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.965735,0.000000,0.0,0.000000,0.000000,RAV4,Edmunds,The tailgate rattles like no SUV I’ve ever own...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4637,RAV4,Edmunds,I purchased my 2021 Toyota Rav4 new in August....,0.968101,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,RAV4,Edmunds,I purchased my 2021 Toyota Rav4 new in August....,0.000000,0.000000,0.304392,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4638,RAV4,Edmunds,"First, the fuel economy is great. Although it ...",0.935105,0.000000,0.000000,0.000000,0.0000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.988952,0.0,0.000000,0.000000,RAV4,Edmunds,"First, the fuel economy is great. Although it ...",0.000000,0.000000,0.000000,0.000000,0.0,0.278976,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:
cars_kbb.replace(0, np.nan, inplace=True)
cars_kbb = cars_kbb.rename(columns={'Souce': 'Source'})
cars_kbb.loc['Mean'] = cars_kbb.mean()
cars_kbb

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  This is separate from the ipykernel package so we can avoid doing imports until

,Model,Source,Comment,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,Model,Source,Comment,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
0,Rogue,Cars,I’ve had my 2021 Rogue SL with the premium pac...,NaN,0.977574,NaN,0.994457,NaN,NaN,NaN,0.921304,NaN,NaN,NaN,NaN,NaN,0.987648,NaN,NaN,NaN,Rogue,Cars,I’ve had my 2021 Rogue SL with the premium pac...,NaN,NaN,0.896185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rogue,Cars,I have to preface this by saying I purchased a...,NaN,0.671533,NaN,NaN,NaN,0.934069,NaN,0.366737,NaN,NaN,NaN,NaN,NaN,0.736786,NaN,NaN,0.099225,Rogue,Cars,I have to preface this by saying I purchased a...,0.376898,0.176889,NaN,NaN,NaN,0.505428,0.568424,0.898860,0.720507,NaN,NaN,0.674960
2,Rogue,Cars,Recently traded in my 2016 for the new redesig...,NaN,NaN,0.972520,0.724667,0.867300,NaN,NaN,NaN,NaN,0.995070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rogue,Cars,Recently traded in my 2016 for the new redesig...,NaN,NaN,0.806745,NaN,NaN,NaN,NaN,NaN,NaN,0.957378,NaN,NaN
3,Rogue,Cars,Meets our needs comfortable stylish love the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rogue,Cars,Meets our needs comfortable stylish love the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Rogue,Cars,Always have been a huge fan of Rogues but I ab...,0.994991,NaN,0.984983,NaN,NaN,0.975976,NaN,0.991613,NaN,NaN,0.998625,0.966145,NaN,0.604196,NaN,0.241507,NaN,Rogue,Cars,Always have been a huge fan of Rogues but I ab...,0.997381,0.304090,0.936501,0.853579,NaN,NaN,0.968310,0.836067,0.978573,0.992617,0.030481,0.036311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4635,RAV4,Edmunds,I have a 2021 Rav 4 Hybrid with 6000 kilometer...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RAV4,Edmunds,I have a 2021 Rav 4 Hybrid with 6000 kilometer...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4636,RAV4,Edmunds,The tailgate rattles like no SUV I’ve ever own...,0.981198,0.557962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.965735,NaN,NaN,NaN,NaN,RAV4,Edmunds,The tailgate rattles like no SUV I’ve ever own...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4637,RAV4,Edmunds,I purchased my 2021 Toyota Rav4 new in August....,0.968101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RAV4,Edmunds,I purchased my 2021 Toyota Rav4 new in August....,NaN,NaN,0.304392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4638,RAV4,Edmunds,"First, the fuel economy is great. Although it ...",0.935105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.988952,NaN,NaN,NaN,RAV4,Edmunds,"First, the fuel economy is great. Although it ...",NaN,NaN,NaN,NaN,NaN,0.278976,NaN,NaN,NaN,NaN,NaN,NaN
Mean,NaN,NaN,NaN,0.908179,0.634941,0.845733,0.899324,0.890906,0.906143,0.594118,0.789482,0.959263,0.871068,0.923621,0.824607,0.676245,0.859388,0.61235,0.554808,0.715314,NaN,NaN,NaN,0.894773,0.353382,0.663092,0.789255,0.720679,0.831532,0.820992,0.667028,0.778174,0.753777,0.343729,0.429533

In [ ]:
cars_kbb.loc['Mean','Source'] = 'Car Review Websites'
cars_kbb.loc['Mean','Model'] = 'Mean'

In [ ]:
cars_kbb

,Model,Source,Comment,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,Model,Source,Comment,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
0,Rogue,Cars,I’ve had my 2021 Rogue SL with the premium pac...,NaN,0.977574,NaN,0.994457,NaN,NaN,NaN,0.921304,NaN,NaN,NaN,NaN,NaN,0.987648,NaN,NaN,NaN,Rogue,Cars,I’ve had my 2021 Rogue SL with the premium pac...,NaN,NaN,0.896185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rogue,Cars,I have to preface this by saying I purchased a...,NaN,0.671533,NaN,NaN,NaN,0.934069,NaN,0.366737,NaN,NaN,NaN,NaN,NaN,0.736786,NaN,NaN,0.099225,Rogue,Cars,I have to preface this by saying I purchased a...,0.376898,0.176889,NaN,NaN,NaN,0.505428,0.568424,0.898860,0.720507,NaN,NaN,0.674960
2,Rogue,Cars,Recently traded in my 2016 for the new redesig...,NaN,NaN,0.972520,0.724667,0.867300,NaN,NaN,NaN,NaN,0.995070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rogue,Cars,Recently traded in my 2016 for the new redesig...,NaN,NaN,0.806745,NaN,NaN,NaN,NaN,NaN,NaN,0.957378,NaN,NaN
3,Rogue,Cars,Meets our needs comfortable stylish love the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rogue,Cars,Meets our needs comfortable stylish love the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Rogue,Cars,Always have been a huge fan of Rogues but I ab...,0.994991,NaN,0.984983,NaN,NaN,0.975976,NaN,0.991613,NaN,NaN,0.998625,0.966145,NaN,0.604196,NaN,0.241507,NaN,Rogue,Cars,Always have been a huge fan of Rogues but I ab...,0.997381,0.304090,0.936501,0.853579,NaN,NaN,0.968310,0.836067,0.978573,0.992617,0.030481,0.036311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4635,RAV4,Edmunds,I have a 2021 Rav 4 Hybrid with 6000 kilometer...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RAV4,Edmunds,I have a 2021 Rav 4 Hybrid with 6000 kilometer...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4636,RAV4,Edmunds,The tailgate rattles like no SUV I’ve ever own...,0.981198,0.557962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.965735,NaN,NaN,NaN,NaN,RAV4,Edmunds,The tailgate rattles like no SUV I’ve ever own...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4637,RAV4,Edmunds,I purchased my 2021 Toyota Rav4 new in August....,0.968101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RAV4,Edmunds,I purchased my 2021 Toyota Rav4 new in August....,NaN,NaN,0.304392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4638,RAV4,Edmunds,"First, the fuel economy is great. Although it ...",0.935105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.988952,NaN,NaN,NaN,RAV4,Edmunds,"First, the fuel economy is great. Although it ...",NaN,NaN,NaN,NaN,NaN,0.278976,NaN,NaN,NaN,NaN,NaN,NaN
Mean,Mean,Car Review Websites,NaN,0.908179,0.634941,0.845733,0.899324,0.890906,0.906143,0.594118,0.789482,0.959263,0.871068,0.923621,0.824607,0.676245,0.859388,0.61235,0.554808,0.715314,Mean,Car Review Websites,NaN,0.894773,0.353382,0.663092,0.789255,0.720679,0.831532,0.820992,0.667028,0.778174,0.753777,0.343729,0.429533

In [ ]:
cars_kbb = cars_kbb.loc[:,~cars_kbb.columns.duplicated()].copy()

In [ ]:
cars_kbb

,Model,Source,Comment,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
0,Rogue,Cars,I’ve had my 2021 Rogue SL with the premium pac...,NaN,0.977574,NaN,0.994457,NaN,NaN,NaN,0.921304,NaN,NaN,NaN,NaN,NaN,0.987648,NaN,NaN,NaN,NaN,NaN,0.896185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rogue,Cars,I have to preface this by saying I purchased a...,NaN,0.671533,NaN,NaN,NaN,0.934069,NaN,0.366737,NaN,NaN,NaN,NaN,NaN,0.736786,NaN,NaN,0.099225,0.376898,0.176889,NaN,NaN,NaN,0.505428,0.568424,0.898860,0.720507,NaN,NaN,0.674960
2,Rogue,Cars,Recently traded in my 2016 for the new redesig...,NaN,NaN,0.972520,0.724667,0.867300,NaN,NaN,NaN,NaN,0.995070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.806745,NaN,NaN,NaN,NaN,NaN,NaN,0.957378,NaN,NaN
3,Rogue,Cars,Meets our needs comfortable stylish love the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Rogue,Cars,Always have been a huge fan of Rogues but I ab...,0.994991,NaN,0.984983,NaN,NaN,0.975976,NaN,0.991613,NaN,NaN,0.998625,0.966145,NaN,0.604196,NaN,0.241507,NaN,0.997381,0.304090,0.936501,0.853579,NaN,NaN,0.968310,0.836067,0.978573,0.992617,0.030481,0.036311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4635,RAV4,Edmunds,I have a 2021 Rav 4 Hybrid with 6000 kilometer...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4636,RAV4,Edmunds,The tailgate rattles like no SUV I’ve ever own...,0.981198,0.557962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.965735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4637,RAV4,Edmunds,I purchased my 2021 Toyota Rav4 new in August....,0.968101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.304392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4638,RAV4,Edmunds,"First, the fuel economy is great. Although it ...",0.935105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.988952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.278976,NaN,NaN,NaN,NaN,NaN,NaN
Mean,Mean,Car Review Websites,NaN,0.908179,0.634941,0.845733,0.899324,0.890906,0.906143,0.594118,0.789482,0.959263,0.871068,0.923621,0.824607,0.676245,0.859388,0.61235,0.554808,0.715314,0.894773,0.353382,0.663092,0.789255,0.720679,0.831532,0.820992,0.667028,0.778174,0.753777,0.343729,0.429533

In [ ]:
cars_kbb.to_csv('car_review_sites_v3.csv', index = 'False')

In [ ]:
cars_kbb

,Model,Source,Comment,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
0,Rogue,Cars,I’ve had my 2021 Rogue SL with the premium pac...,NaN,0.977574,NaN,0.994457,NaN,NaN,NaN,0.921304,NaN,NaN,NaN,NaN,NaN,0.987648,NaN,NaN,NaN,NaN,NaN,0.896185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rogue,Cars,I have to preface this by saying I purchased a...,NaN,0.671533,NaN,NaN,NaN,0.934069,NaN,0.366737,NaN,NaN,NaN,NaN,NaN,0.736786,NaN,NaN,0.099225,0.376898,0.176889,NaN,NaN,NaN,0.505428,0.568424,0.898860,0.720507,NaN,NaN,0.674960
2,Rogue,Cars,Recently traded in my 2016 for the new redesig...,NaN,NaN,0.972520,0.724667,0.867300,NaN,NaN,NaN,NaN,0.995070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.806745,NaN,NaN,NaN,NaN,NaN,NaN,0.957378,NaN,NaN
3,Rogue,Cars,Meets our needs comfortable stylish love the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Rogue,Cars,Always have been a huge fan of Rogues but I ab...,0.994991,NaN,0.984983,NaN,NaN,0.975976,NaN,0.991613,NaN,NaN,0.998625,0.966145,NaN,0.604196,NaN,0.241507,NaN,0.997381,0.304090,0.936501,0.853579,NaN,NaN,0.968310,0.836067,0.978573,0.992617,0.030481,0.036311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4635,RAV4,Edmunds,I have a 2021 Rav 4 Hybrid with 6000 kilometer...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4636,RAV4,Edmunds,The tailgate rattles like no SUV I’ve ever own...,0.981198,0.557962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.965735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4637,RAV4,Edmunds,I purchased my 2021 Toyota Rav4 new in August....,0.968101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.304392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4638,RAV4,Edmunds,"First, the fuel economy is great. Although it ...",0.935105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.988952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.278976,NaN,NaN,NaN,NaN,NaN,NaN
Mean,Mean,Car Review Websites,NaN,0.908179,0.634941,0.845733,0.899324,0.890906,0.906143,0.594118,0.789482,0.959263,0.871068,0.923621,0.824607,0.676245,0.859388,0.61235,0.554808,0.715314,0.894773,0.353382,0.663092,0.789255,0.720679,0.831532,0.820992,0.667028,0.778174,0.753777,0.343729,0.429533

In [ ]:
cars_avg = cars_kbb.groupby(['Model']).mean()
cars_avg

,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
Model,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Bronco Sport,0.908963,0.629949,0.820971,0.904904,0.884625,0.947002,0.818063,0.744519,0.984958,0.883051,0.876247,0.799608,0.635796,0.848309,0.605449,0.407779,0.729448,0.846903,0.375687,0.675811,0.784128,0.858340,0.898811,0.835729,0.810448,0.878547,0.892657,0.516113,0.546860
CR-V,0.925410,0.730070,0.958938,0.818390,0.789002,0.961774,0.590668,0.734635,0.942814,0.906903,0.935179,0.879630,0.557221,0.837161,0.645195,0.614019,0.703298,0.929795,0.519106,0.800996,0.745801,0.817239,0.922720,0.957255,0.550142,0.799300,0.773863,0.503291,0.282777
CX-5,0.957868,0.548921,0.803078,0.926608,0.938238,0.931440,0.504481,0.858162,0.973749,0.908644,0.951779,0.733633,0.597964,0.849420,0.644011,0.409658,0.689924,0.964213,0.348154,0.589310,0.574387,0.748096,0.902926,0.756072,0.803490,0.871281,0.773868,0.294762,0.416122
Equinox,0.963950,0.667850,0.851036,0.943220,0.969580,0.961913,0.677692,0.844106,0.994846,0.849403,0.911354,0.929184,0.887072,0.950529,0.678862,0.727853,0.847078,0.959099,0.050330,0.645288,0.895118,0.827819,0.755448,0.863409,0.708762,0.833154,0.878334,0.104974,0.494892
Escape,0.979978,0.690050,0.793839,0.958570,0.971416,0.937577,0.623541,0.796607,0.994506,0.823714,0.891151,0.956117,0.938938,0.937905,0.513351,0.920814,0.811421,0.989422,0.127304,0.637064,0.795132,0.869291,0.558675,0.827025,0.695076,0.773418,0.974666,0.242875,0.449611
Forester,0.932115,0.613383,0.935216,0.897826,0.812883,0.880064,0.652661,0.847233,0.941046,0.861740,0.933082,0.859017,0.510015,0.792335,0.452196,0.445153,0.840463,0.924065,0.494034,0.644448,0.860284,0.746167,0.876934,0.932072,0.731229,0.898698,0.863538,0.491969,0.462602
Mean,0.908179,0.634941,0.845733,0.899324,0.890906,0.906143,0.594118,0.789482,0.959263,0.871068,0.923621,0.824607,0.676245,0.859388,0.612350,0.554808,0.715314,0.894773,0.353382,0.663092,0.789255,0.720679,0.831532,0.820992,0.667028,0.778174,0.753777,0.343729,0.429533
RAV4,0.764242,0.568922,0.822090,0.879170,0.893424,0.892868,0.504818,0.828912,0.987341,0.844515,0.969709,0.799168,0.779063,0.947231,0.823658,0.451420,0.795853,0.831231,0.358672,0.589145,0.879168,0.642008,0.842388,0.812369,0.761501,0.521668,0.569216,0.396260,0.461458
Rogue,0.893634,0.575767,0.925818,0.930666,0.911031,0.872481,0.573127,0.796583,0.900158,0.898128,0.878442,0.802267,0.720440,0.830680,0.408410,0.722185,0.588787,0.859171,0.292368,0.653269,0.863350,0.756887,0.770481,0.785660,0.585628,0.732590,0.819186,0.436360,0.559032
Sportage,0.945711,0.795828,0.725782,0.929159,0.928021,0.976886,0.863762,0.768471,0.980700,0.865065,0.913351,0.822730,0.486879,0.864040,0.804829,0.735924,0.714400,0.873211,0.259481,0.800662,0.930242,0.358754,0.913795,0.777361,0.829271,0.890447,0.878377,0.288448,0.509716
Tucson,0.926583,0.697108,0.715283,0.902192,0.890944,0.793640,0.587714,0.748620,0.883747,0.817491,0.870692,0.748175,0.631043,0.737951,0.346284,0.357592,0.599226,0.814392,0.266114,0.705695,0.659121,0.614022,0.642727,0.605720,0.461089,0.701629,0.619754,0.256984,0.289399

In [ ]:
cars_count = cars_kbb.groupby(['Model']).count()
cars_count

,Source,Comment,dependable,lasts long,value for money,quality fit and finish,attractive styling,safe,retains resale value,driver comfort,fun to drive,advanced features,responsive handling,prestigious,dealerships,fuel efficient,quick acceleration,environmentally friendly,affordable,trusted,leader,responsible,confident,innovative,exciting,practical,adventurous,passionate,distinctive,youthful,aggressive
Model,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Bronco Sport,197,197,21,37,10,27,34,16,5,49,48,29,40,11,12,33,12,8,13,13,4,13,16,5,16,9,18,36,12,9,20
CR-V,915,915,155,80,75,81,80,47,27,236,154,193,130,43,26,103,61,24,70,60,7,53,118,50,47,59,61,86,69,7,66
CX-5,527,527,70,78,50,91,103,33,26,55,144,85,109,68,35,77,53,8,52,38,26,26,21,14,47,33,42,59,77,21,73
Equinox,377,377,24,46,29,29,41,28,25,50,32,63,76,35,18,35,12,3,17,23,1,34,15,5,24,21,8,25,22,11,23
Escape,332,328,5,41,23,13,29,20,23,32,11,44,52,32,16,25,9,2,8,15,1,30,5,2,9,11,2,10,10,10,16
Forester,353,353,67,66,25,83,70,72,18,104,78,110,77,34,14,62,24,14,19,43,12,32,42,15,40,34,29,48,31,14,33
Mean,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
RAV4,819,819,88,110,11,119,110,31,42,151,248,97,126,45,45,131,28,3,48,48,5,101,45,23,50,17,44,60,66,9,93
Rogue,321,321,51,58,29,61,68,55,25,78,59,66,57,32,18,47,20,21,28,31,16,44,47,40,35,39,33,39,41,20,50
Sportage,394,394,55,25,27,77,47,30,7,65,71,44,87,14,19,61,24,2,19,16,2,20,18,11,26,44,18,25,25,9,23
Tucson,404,404,102,58,47,67,64,38,20,67,78,92,59,40,26,66,23,12,32,47,13,37,38,26,36,34,38,48,49,22,42

In [ ]:
with pd.ExcelWriter('cars avg results.xlsx') as writer:
  cars_avg.to_excel(writer, sheet_name='cars_avg')
  cars_count.to_excel(writer, sheet_name='cars_count')