<a href="https://colab.research.google.com/github/BFvandy/Nissan-Text-Mining-POC-with-Transformer/blob/main/SW_Pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prep

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
!pip install langdetect
from langdetect import detect
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     |████████████████████████████████| 981 kB 3.9 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from langdetect) (1.15.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993242 sha256=ddcbfcbe4a2dac243253431c3e7bf0dde4c2234f71837ecc8394046e872a721f
  Stored in directory: /root/.cache/pip/wheels/c5/96/8a/f90c59ed25d75e50a8c10a1b1c2d4c402e4dacfa87f3aff36a
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
cur_path = "/content/drive/My Drive/Nissan Internship/SW 2020-2022 Verbatim Small SUV"
os.chdir(cur_path)
!pwd

/content/drive/My Drive/Nissan Internship/SW 2020-2022 Verbatim Small SUV

# Pre-processing

In [ ]:
comments_2022 = pd.read_csv('SW_2022_verbatim_small_suv.csv', skiprows=12)
comments_2021 = pd.read_csv('SW_2021_verbatim_small_suv.csv', skiprows=12)
comments_2020 = pd.read_csv('SW_2020_verbatim_small_suv.csv', skiprows=12)

In [ ]:
comments_2022.insert(1, 'Study Year', '2022')
comments_2022.head(5)

,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Verbatim Text
0,Honda CR-V Special Edition FWD,2022,2021,Honda Civic,2019.0,Honda HR-V,2022.0,Sentiment Not Calculated,Age 41,Female,White,Income Unknown,The engine start stop/ gas save mode is not ve...
1,Nissan Rogue SV AWD,2022,2021,Ford Fusion,2012.0,Toyota Highlander,2021.0,Sentiment Not Calculated,Age 35,Male,White,"$100,001 - $125,000",We were not told the price of the vehicle goin...
2,Nissan Rogue S AWD,2022,2021,Chevrolet Spark,2016.0,Hyundai Santa Fe,2021.0,Sentiment Not Calculated,Age 57,Male,White,Income Unknown,My Nissan Rogue is the perfect balance between...
3,Honda CR-V EX/EX-L FWD,2022,2022,Nissan Versa Note (Hatchback),2018.0,Lexus LX,2022.0,Sentiment Not Calculated,Age 49,Female,Asian,"$65,001 - $70,000",I wish :\n1.there is a CD player installed. T...
4,Honda CR-V EX/EX-L FWD,2022,2022,(None),NaN,Honda Civic,2015.0,Sentiment Not Calculated,Age 54,Female,White,"$200,001 - $300,000","The 2022 Honda CRV is a nice looking car, with..."

In [ ]:
comments_2021.insert(1, 'Study Year', '2021')
comments_2021.head(5)

,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Verbatim Text
0,Toyota RAV4 FWD,2021,2021,Pontiac Grand Prix,2004.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age Unknown,Gender Unknown,White,Income Unknown,I made a list of items/features which I like &...
1,Subaru Forester Limited AWD,2021,2021,Toyota 4Runner,2005.0,Toyota RAV4,2021.0,Sentiment Not Calculated,Age 65,Female,White,Income Unknown,We sent a letter with all of our concerns. He...
2,Honda CR-V EX/EX-L AWD,2021,2021,Honda CR-V,2009.0,(None),NaN,Sentiment Not Calculated,Age 52,Female,White,"$125,001 - $150,000",4-20-2021\nLeft voicemail for a specific sales...
3,Honda CR-V EX/EX-L AWD,2021,2021,Honda CR-V,2009.0,(None),NaN,Sentiment Not Calculated,Age 52,Female,White,"$125,001 - $150,000",4-20-2021\nLeft voicemail for a specific sales...
4,Subaru Forester Sport AWD,2021,2021,Ford Escape,2011.0,(None),NaN,Sentiment Not Calculated,Age 59,Female,White,"$100,001 - $125,000",Overall I am happy with it. I feel safe drivin...

In [ ]:
comments_2020.insert(1, 'Study Year', '2020')
comments_2020.head(5)

,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Verbatim Text
0,Honda CR-V EX/EX-L AWD,2020,2020,Honda Odyssey,2008.0,Honda Pilot,2020.0,Sentiment Not Calculated,Age 63,Female,White,"$50,001 - $55,000","The 2008 Honda Odyssey, 2009 CR-V, and 2013 Ci..."
1,Mazda CX-5 AWD,2020,2019,Mazda CX-5,2014.0,Acura RDX,2020.0,Sentiment Not Calculated,Age 30,Male,White,"$100,001 - $125,000",My first experience at Heritage Mazda of Bel A...
2,Nissan Rogue SV FWD,2020,2020,Nissan Rogue,2015.0,Chevrolet Suburban,2015.0,Sentiment Not Calculated,Age 44,Male,Hispanic,"$90,001 - $100,000",I bought two vehicles from this dealer! I have...
3,Subaru Forester Base AWD,2020,2020,Honda Accord,2005.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 33,Male,White,"$20,001 - $25,000",A few things kept this from being my dream pur...
4,Honda CR-V EX/EX-L AWD,2020,2020,Honda CR-V,NaN,(None),NaN,Sentiment Not Calculated,Age Unknown,Female,NaN,Income Unknown,My sales experience sucked. I was told that pr...

In [ ]:
SW_dfs = [comments_2022, comments_2021, comments_2020]

In [ ]:
for df in SW_dfs:
    print(df.shape)

(15901, 13)
(59577, 13)
(31526, 13)

In [ ]:
all_SW_cmt = pd.concat(SW_dfs)
all_SW_cmt = all_SW_cmt.reset_index()

In [ ]:
all_SW_cmt

,index,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Verbatim Text
0,0,Honda CR-V Special Edition FWD,2022,2021,Honda Civic,2019.0,Honda HR-V,2022.0,Sentiment Not Calculated,Age 41,Female,White,Income Unknown,The engine start stop/ gas save mode is not ve...
1,1,Nissan Rogue SV AWD,2022,2021,Ford Fusion,2012.0,Toyota Highlander,2021.0,Sentiment Not Calculated,Age 35,Male,White,"$100,001 - $125,000",We were not told the price of the vehicle goin...
2,2,Nissan Rogue S AWD,2022,2021,Chevrolet Spark,2016.0,Hyundai Santa Fe,2021.0,Sentiment Not Calculated,Age 57,Male,White,Income Unknown,My Nissan Rogue is the perfect balance between...
3,3,Honda CR-V EX/EX-L FWD,2022,2022,Nissan Versa Note (Hatchback),2018.0,Lexus LX,2022.0,Sentiment Not Calculated,Age 49,Female,Asian,"$65,001 - $70,000",I wish :\n1.there is a CD player installed. T...
4,4,Honda CR-V EX/EX-L FWD,2022,2022,(None),NaN,Honda Civic,2015.0,Sentiment Not Calculated,Age 54,Female,White,"$200,001 - $300,000","The 2022 Honda CRV is a nice looking car, with..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106999,31521,Honda CR-V EX/EX-L FWD,2020,2020,None,18.0,None,16.0,Sentiment Not Calculated,Age 34,Female,Hispanic,"$150,001 - $175,000",G
107000,31522,Honda CR-V EX/EX-L AWD,2020,2019,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.
107001,31523,Honda CR-V EX/EX-L AWD,2020,2019,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.
107002,31524,Honda CR-V LX FWD,2020,2019,Honda CR-V,2015.0,Honda HR-V,2019.0,Sentiment Not Calculated,Age 59,Male,White,"$50,001 - $55,000",I
107003,31525,Nissan Rogue SV AWD,2020,2020,(None),NaN,(None),NaN,Sentiment Not Calculated,Age Unknown,Female,White,Income Unknown,I

In [ ]:
# Normalize Text:
# count word number
# word_n = []
# for text in comments['Verbatim Text']:
#   word_n.append(len(str(text).split()))
# comments['word count'] = word_n
# comments

# don't need to count word number because transformer automatically trims the sentence down to 512 tokens

In [ ]:
# Tag Make and Model
Make = ['Nissan', 'Chevrolet', 'Ford', 'Ford', 'Honda', 'Hyundai', 'Kia', 'Mazda', 'Subaru', 'Toyota']
Model = ['Rogue', 'Equinox', 'Escape', 'Bronco Sport', 'CR-V', 'Tucson', 'Sportage', 'CX-5', 'Forester', 'RAV4']

def tag_model(brand):
  for tag in Model:
    if tag in brand:
      return tag
    else:
      pass

def tag_make(mak):
  for cm in Make:
    if cm in mak:
      return cm
    else:
      pass

mod = []
for i in range(len(all_SW_cmt['Purchased'])):
  brand = all_SW_cmt['Purchased'][i]
  mod.append(tag_model(brand))

all_SW_cmt.insert(0,'Model',mod)

car_make = []
for i in range(len(all_SW_cmt['Purchased'])):
  mak = all_SW_cmt['Purchased'][i]
  car_make.append(tag_make(mak))

all_SW_cmt.insert(0,'Make', car_make)
all_SW_cmt

,Make,Model,index,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Verbatim Text
0,Honda,CR-V,0,Honda CR-V Special Edition FWD,2022,2021,Honda Civic,2019.0,Honda HR-V,2022.0,Sentiment Not Calculated,Age 41,Female,White,Income Unknown,The engine start stop/ gas save mode is not ve...
1,Nissan,Rogue,1,Nissan Rogue SV AWD,2022,2021,Ford Fusion,2012.0,Toyota Highlander,2021.0,Sentiment Not Calculated,Age 35,Male,White,"$100,001 - $125,000",We were not told the price of the vehicle goin...
2,Nissan,Rogue,2,Nissan Rogue S AWD,2022,2021,Chevrolet Spark,2016.0,Hyundai Santa Fe,2021.0,Sentiment Not Calculated,Age 57,Male,White,Income Unknown,My Nissan Rogue is the perfect balance between...
3,Honda,CR-V,3,Honda CR-V EX/EX-L FWD,2022,2022,Nissan Versa Note (Hatchback),2018.0,Lexus LX,2022.0,Sentiment Not Calculated,Age 49,Female,Asian,"$65,001 - $70,000",I wish :\n1.there is a CD player installed. T...
4,Honda,CR-V,4,Honda CR-V EX/EX-L FWD,2022,2022,(None),NaN,Honda Civic,2015.0,Sentiment Not Calculated,Age 54,Female,White,"$200,001 - $300,000","The 2022 Honda CRV is a nice looking car, with..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106999,Honda,CR-V,31521,Honda CR-V EX/EX-L FWD,2020,2020,None,18.0,None,16.0,Sentiment Not Calculated,Age 34,Female,Hispanic,"$150,001 - $175,000",G
107000,Honda,CR-V,31522,Honda CR-V EX/EX-L AWD,2020,2019,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.
107001,Honda,CR-V,31523,Honda CR-V EX/EX-L AWD,2020,2019,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.
107002,Honda,CR-V,31524,Honda CR-V LX FWD,2020,2019,Honda CR-V,2015.0,Honda HR-V,2019.0,Sentiment Not Calculated,Age 59,Male,White,"$50,001 - $55,000",I
107003,Nissan,Rogue,31525,Nissan Rogue SV AWD,2020,2020,(None),NaN,(None),NaN,Sentiment Not Calculated,Age Unknown,Female,White,Income Unknown,I

In [ ]:
all_SW_cmt = all_SW_cmt.drop('index', axis=1)

In [ ]:
all_SW_cmt

,Make,Model,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Verbatim Text
0,Honda,CR-V,Honda CR-V Special Edition FWD,2022,2021,Honda Civic,2019.0,Honda HR-V,2022.0,Sentiment Not Calculated,Age 41,Female,White,Income Unknown,The engine start stop/ gas save mode is not ve...
1,Nissan,Rogue,Nissan Rogue SV AWD,2022,2021,Ford Fusion,2012.0,Toyota Highlander,2021.0,Sentiment Not Calculated,Age 35,Male,White,"$100,001 - $125,000",We were not told the price of the vehicle goin...
2,Nissan,Rogue,Nissan Rogue S AWD,2022,2021,Chevrolet Spark,2016.0,Hyundai Santa Fe,2021.0,Sentiment Not Calculated,Age 57,Male,White,Income Unknown,My Nissan Rogue is the perfect balance between...
3,Honda,CR-V,Honda CR-V EX/EX-L FWD,2022,2022,Nissan Versa Note (Hatchback),2018.0,Lexus LX,2022.0,Sentiment Not Calculated,Age 49,Female,Asian,"$65,001 - $70,000",I wish :\n1.there is a CD player installed. T...
4,Honda,CR-V,Honda CR-V EX/EX-L FWD,2022,2022,(None),NaN,Honda Civic,2015.0,Sentiment Not Calculated,Age 54,Female,White,"$200,001 - $300,000","The 2022 Honda CRV is a nice looking car, with..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106999,Honda,CR-V,Honda CR-V EX/EX-L FWD,2020,2020,None,18.0,None,16.0,Sentiment Not Calculated,Age 34,Female,Hispanic,"$150,001 - $175,000",G
107000,Honda,CR-V,Honda CR-V EX/EX-L AWD,2020,2019,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.
107001,Honda,CR-V,Honda CR-V EX/EX-L AWD,2020,2019,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.
107002,Honda,CR-V,Honda CR-V LX FWD,2020,2019,Honda CR-V,2015.0,Honda HR-V,2019.0,Sentiment Not Calculated,Age 59,Male,White,"$50,001 - $55,000",I
107003,Nissan,Rogue,Nissan Rogue SV AWD,2020,2020,(None),NaN,(None),NaN,Sentiment Not Calculated,Age Unknown,Female,White,Income Unknown,I

In [ ]:
# To drop a column:
# comments_score = comments_score.drop('M', axis=1)

# To insert a column:
# df.insert(2, 'Places', places)
# df = df.drop('column_name', axis=1)

# check lenghth by word count
# comments.groupby('word count')['Make'].count()

# comments.insert(loc=0, column='row_num', value=np.arange(len(comments)))
# comments = comments.reset_index()

In [ ]:
# check lenghth:
len(all_SW_cmt)

107004

In [ ]:
# Drop NA for all the functional attributes

all_SW_cmt.dropna(subset = ['Verbatim Text'])
all_SW_cmt

,Make,Model,Purchased,Study Year,Purchased Year,Disposed,Disposed Model Year,Rejected,Rejected Model Year,Sentiment,Age Range,Gender,Ethnicity,Income Bracket,Verbatim Text
0,Honda,CR-V,Honda CR-V Special Edition FWD,2022,2021,Honda Civic,2019.0,Honda HR-V,2022.0,Sentiment Not Calculated,Age 41,Female,White,Income Unknown,The engine start stop/ gas save mode is not ve...
1,Nissan,Rogue,Nissan Rogue SV AWD,2022,2021,Ford Fusion,2012.0,Toyota Highlander,2021.0,Sentiment Not Calculated,Age 35,Male,White,"$100,001 - $125,000",We were not told the price of the vehicle goin...
2,Nissan,Rogue,Nissan Rogue S AWD,2022,2021,Chevrolet Spark,2016.0,Hyundai Santa Fe,2021.0,Sentiment Not Calculated,Age 57,Male,White,Income Unknown,My Nissan Rogue is the perfect balance between...
3,Honda,CR-V,Honda CR-V EX/EX-L FWD,2022,2022,Nissan Versa Note (Hatchback),2018.0,Lexus LX,2022.0,Sentiment Not Calculated,Age 49,Female,Asian,"$65,001 - $70,000",I wish :\n1.there is a CD player installed. T...
4,Honda,CR-V,Honda CR-V EX/EX-L FWD,2022,2022,(None),NaN,Honda Civic,2015.0,Sentiment Not Calculated,Age 54,Female,White,"$200,001 - $300,000","The 2022 Honda CRV is a nice looking car, with..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106999,Honda,CR-V,Honda CR-V EX/EX-L FWD,2020,2020,None,18.0,None,16.0,Sentiment Not Calculated,Age 34,Female,Hispanic,"$150,001 - $175,000",G
107000,Honda,CR-V,Honda CR-V EX/EX-L AWD,2020,2019,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.
107001,Honda,CR-V,Honda CR-V EX/EX-L AWD,2020,2019,GMC Terrain,2013.0,Honda CR-V,2020.0,Sentiment Not Calculated,Age 42,Male,White,"$100,001 - $125,000",.
107002,Honda,CR-V,Honda CR-V LX FWD,2020,2019,Honda CR-V,2015.0,Honda HR-V,2019.0,Sentiment Not Calculated,Age 59,Male,White,"$50,001 - $55,000",I
107003,Nissan,Rogue,Nissan Rogue SV AWD,2020,2020,(None),NaN,(None),NaN,Sentiment Not Calculated,Age Unknown,Female,White,Income Unknown,I

In [ ]:
all_SW_cmt.groupby('Model')['Verbatim Text'].count()

Model
Bronco Sport     1171
CR-V            66832
CX-5             3488
Equinox          2183
Escape           1609
Forester         3919
RAV4             2941
Rogue           18237
Sportage         1528
Tucson           2259
Name: Verbatim Text, dtype: int64

In [ ]:
all_SW_cmt.to_csv('all_SW_cmt.csv', index = False)